# Generated by Django 3.2.25 on 2025-10-27 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networknode',
            name='debt',
        ),
        migrations.RemoveField(
            model_name='networknode',
            name='supplier',
        ),
        migrations.CreateModel(
            name='SupplierLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Задолженность')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_links', to='network.networknode', verbose_name='Клиент')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_links', to='network.networknode', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Связь Поставщик-Клиент',
                'verbose_name_plural': 'Связи Поставщик-Клиент',
                'unique_together': {('supplier', 'client')},
            },
        ),
        migrations.AddField(
            model_name='networknode',
            name='suppliers',
            field=models.ManyToManyField(related_name='clients', through='network.SupplierLink', to='network.NetworkNode', verbose_name='Поставщики'),
        ),
    ]
